name: Build Geode Mod

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@v2
        with:
          combine: true
          cli: nightly
