name: Build Geode Mod
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Android Mod
        uses: geode-sdk/build-mod@v1
        with:
          cli: nightly
          platform: android64
          combine: false
